server:
  port: 8081
spring:
  datasource:
    platform: mariadb
    drivateClassNam: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://127.0.0.1:3306/test
    username: root
    password: myM4ri4DB!
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true